#!/usr/bin/env bash
set -euo pipefail

DEFAULT_SEMVER="1.0.0"
MODE=""
TAG=""
WRITE_XCCONFIG=""
EXPORT=0

usage() {
  cat <<'EOF'
Usage: compute-version.sh --mode MODE [options]

Modes:
  local-auto    Detect suffix from Xcode build context (dev/test/local)
  ci-test       CI PR/push: semver-hash
  ci-release    CI release: semver from tag

Options:
  --tag TAG             Release tag (e.g. v1.0.0); used with ci-release
  --write-xcconfig PATH Write MARKETING_VERSION and CURRENT_PROJECT_VERSION to xcconfig
  --export              Print shell assignments to stdout (for eval in CI)
  -h, --help            Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode)
      MODE="$2"
      shift 2
      ;;
    --tag)
      TAG="$2"
      shift 2
      ;;
    --write-xcconfig)
      WRITE_XCCONFIG="$2"
      shift 2
      ;;
    --export)
      EXPORT=1
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "$MODE" ]]; then
  echo "Missing required --mode" >&2
  usage >&2
  exit 1
fi

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

strip_v_prefix() {
  local value="$1"
  value="${value#v}"
  echo "$value"
}

resolve_semver() {
  if [[ "$MODE" == "ci-release" ]]; then
    if [[ -z "$TAG" ]]; then
      echo "ci-release requires --tag" >&2
      exit 1
    fi
    strip_v_prefix "$TAG"
    return
  fi

  if git describe --exact-match --tags HEAD >/dev/null 2>&1; then
    strip_v_prefix "$(git describe --exact-match --tags HEAD)"
    return
  fi

  if nearest_tag="$(git describe --tags --abbrev=0 --match 'v*' 2>/dev/null)"; then
    strip_v_prefix "$nearest_tag"
    return
  fi

  echo "$DEFAULT_SEMVER"
}

resolve_hash() {
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    git rev-parse --short=7 HEAD
  else
    echo "unknown"
  fi
}

resolve_local_suffix() {
  if [[ "${ACTION:-}" == "install" ]]; then
    echo "local"
  elif [[ "${BUILD_FOR_TESTING:-}" == "YES" ]]; then
    echo "test"
  else
    echo "dev"
  fi
}

semver="$(resolve_semver)"
hash="$(resolve_hash)"

case "$MODE" in
  local-auto)
    suffix="$(resolve_local_suffix)"
    marketing_version="${semver}-${suffix}-${hash}"
    project_version="$hash"
    ;;
  ci-test)
    marketing_version="${semver}-${hash}"
    project_version="$hash"
    ;;
  ci-release)
    marketing_version="$semver"
    project_version="$semver"
    ;;
  *)
    echo "Unknown mode: $MODE" >&2
    exit 1
    ;;
esac

if [[ -n "$WRITE_XCCONFIG" ]]; then
  mkdir -p "$(dirname "$WRITE_XCCONFIG")"
  cat >"$WRITE_XCCONFIG" <<EOF
// Generated by Scripts/compute-version.sh — do not edit manually.
MARKETING_VERSION = $marketing_version
CURRENT_PROJECT_VERSION = $project_version
EOF
fi

if [[ "$EXPORT" -eq 1 ]]; then
  printf 'MARKETING_VERSION=%q\n' "$marketing_version"
  printf 'CURRENT_PROJECT_VERSION=%q\n' "$project_version"
fi
